version: "3.8"

services:
  postgres:
    container_name: "stash-bot-postgres"
    image: "postgres:11"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data/"
    environment:
      POSTGRES_PASSWORD: password

  bot:
    container_name: stash-bot-bot
    image: node:16
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - ./bot/.env
    working_dir: /srv/bot
    volumes:
      - .:/srv/bot
    command: yarn workspace bot dev

volumes:
  pgdata: {}
