Resources:
  GitHubOIDC:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ThumbprintList:
        - a031c46782e6e6c662c2c87c76da9aa62ccabd8e
      ClientIdList:
        - sts.amazonaws.com

  CloudformationDeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: github-oidc-role
      MaxSessionDuration: 3600
      Policies:
        - PolicyName: inline
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRoleWithWebIdentity
                Resource:
                  - "*"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GitHubOIDC
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: repo:Beta-Folf/stash-bot:ref:refs/heads/main

  ECRUser:
    Type: AWS::IAM::User
    Properties:
      UserName: stash-bot-ecr

Outputs:
  CloudformationDeploymentIAMRole:
    Description: The ID of the cloud formation deployment IAM role
    Value: !Ref CloudformationDeploymentRole
    Export:
      Name: "stash-bot-cloudformation-deployment-iam-role"
  ECRIAMUser:
    Description: The ID of the ECR IAM user
    Value: !Ref ECRUser
    Export:
      Name: "stash-bot-ecr-iam-user"
