name: Build Docker Image

on: [workflow_dispatch]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

      - name: Log into Digital Ocean Container Registry
        run: doctl registry login

      - uses: actions/checkout@v2

      - name: Start Deployment
        uses: bobheadxi/deployments@v0.6.2
        id: deployment
        with:
          step: start
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          env: production

      - run: cd ./bot

      - name: Build Docker Image
        run: docker build ./bot -t stash-bot

      - name: Tag Docker Image
        run: docker tag stash-bot registry.digitalocean.com/stash-bot/bot

      - name: Publish Docker Image to Container Registry
        run: docker push registry.digitalocean.com/stash-bot/bot

      - name: SSH into Droplet and Run Bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          script: docker stop bot && docker pull registry.digitalocean.com/stash-bot/bot:latest && docker run -e TOKEN=$TOKEN -d --name bot registry.digitalocean.com/stash-bot/bot

      - name: Update Deployment Status
        uses: bobheadxi/deployments@v0.6.2
        with:
          step: finish
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
