name: Build Docker Image

on: [workflow_dispatch]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v2

      - name: Start Deployment
        uses: bobheadxi/deployments@v0.6.2
        id: deployment
        with:
          step: start
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          env: production

      - run: cd ./bot

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: betafolf/stash-bot

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./bot
          push: true
          tags: betafolf/stash-bot:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Deployment Status
        uses: bobheadxi/deployments@v0.6.2
        with:
          step: finish
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
