name: Deploy Cloudformation

on:
  push:
    branches:
      - main
    paths:
      - "cloudformation/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-cloudformation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Cloudformation Deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: AWS

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          role-to-assume: ${{ secrets.AWS_CLI_CLOUDFORMATION_ROLE }}
          aws-region: us-east-1

      - name: Deploy Cloudformation
        run: |
          aws cloudformation deploy \
          --template-file ./cloudformation/main.yml \
          --stack-name stash-bot \
          --capabilities CAPABILITY_NAMED_IAM

      - name: Update Deployment Status
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
