name: Deploy Latest Container

on: [workflow_dispatch]

jobs:
  deploy-latest-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Deployment
        uses: bobheadxi/deployments@v0.6.2
        id: deployment
        with:
          step: start
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          env: production

      - name: SSH into Droplet and Run Bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          script: docker stop bot && docker rm bot && docker pull betafolf/stash-bot:latest && docker run -e TOKEN=${{ secrets.DISCORD_TOKEN }} -e DATABASE_URL=${{ secrets.DATABASE_URL }} -d --name bot betafolf/stash-bot:latest

      - name: Update Deployment Status
        uses: bobheadxi/deployments@v0.6.2
        with:
          step: finish
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
