name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

      - name: Log into Digital Ocean Container Registry
        run: doctl registry login

      - uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: node
          package-name: stash-bot
          path: bot

      - name: Start Deployment
        uses: bobheadxi/deployments@v0.6.2
        id: deployment
        if: ${{ always() && steps.release.outputs.release_created }}
        with:
          step: start
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          env: production

      - name: Build Docker Image
        run: docker build ./bot -t stash-bot:$(git rev-parse --short "$GITHUB_SHA")

      - name: Tag Docker Image
        run: docker tag stash-bot:$(git rev-parse --short "$GITHUB_SHA") registry.digitalocean.com/stash-bot/bot

      - name: Publish Docker Image to Container Registry
        run: docker push registry.digitalocean.com/stash-bot/bot

      - name: Update Deployment Status
        uses: bobheadxi/deployments@v0.6.2
        if: ${{ always() && steps.release.outputs.release_created }}
        with:
          step: finish
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
