name: Release Please

on:
  push:
    branches:
      - main
    paths:
      - "bot/**"
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: node
          package-name: stash-bot
          bump-patch-for-minor-pre-major: true

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - name: Start Deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production

        if: ${{ steps.release.outputs.release_created }}

      # Insert your project-specific deployment steps here
      # Be sure to include the if conditional

      - name: Update Deployment Status
        uses: bobheadxi/deployments@v0.4.3
        if: ${{ always() && steps.release.outputs.release_created }}
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
