name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: node
          package-name: stash-bot
          path: bot

      - name: Start Deployment
        uses: bobheadxi/deployments@v0.6.2
        id: deployment
        if: ${{ always() && steps.release.outputs.release_created }}
        with:
          step: start
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          env: production

      - run: cd ./bot

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: betafolf/stash-bot

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./bot
          push: true
          tags: betafolf/stash-bot:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: SSH into Droplet and Run Bot
        if: ${{ steps.release.outputs.release_created }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          script: docker stop bot && docker rm bot && docker pull betafolf/stash-bot:latest && docker run -e TOKEN=${{ secrets.DISCORD_TOKEN }} -e DATABASE_URL=${{ secrets.DATABASE_URL }} -d --name bot betafolf/stash-bot:latest

      - name: Update Deployment Status
        uses: bobheadxi/deployments@v0.6.2
        if: ${{ always() && steps.release.outputs.release_created }}
        with:
          step: finish
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
